name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        distribution: [ 'adopt' ]
        java-version: [ '1.8', '11', '17' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install packages on linux
        run: >
          if [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
            sudo apt-get install -y --no-install-recommends dbus libdbus-glib-1-dev libsecret-tools gnome-keyring
          fi
      - name: setup keystore
        run: ${{ github.workspace }}/setupkeystore.sh    
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
      - name: Maven Install   
        run: mvn --batch-mode --update-snapshots verify
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          name: unittest
          fail_ci_if_error: true
          verbose: true
